### ISSUE TITLE
Feature Request: Expand What The Flag to have an option where all UI Elements have hover Tooltips with the name of the Module that provides them.

### ISSUE THREAD

**Issue by Payden-Pringle** [theripper93/what-the-flag#3]
It'd be neat if What The Flag had a setting where, if you enabled it, when you hover a given UI element, a tooltip told you where it came from. i.e. System for built-in elements, Boss Bar for the boss's bar, Spotlight Omnisearch, etc etc.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
